"""Live usage of instances (CPU, memory, uptime), refreshed by the reconciler.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 23:03:58.003701
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('cpu_usage', sa.Float(), server_default='0', nullable=False))
    op.add_column('instances', sa.Column('memory_used_mb', sa.Integer(), server_default='0', nullable=False))
    op.add_column('instances', sa.Column('uptime_seconds', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'uptime_seconds')
    op.drop_column('instances', 'memory_used_mb')
    op.drop_column('instances', 'cpu_usage')
    # ### end Alembic commands ###
