"""Phase 2a: images (templates), users' SSH public keys, tenant quotas, instance IPs.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 22:14:47.199286
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('provider_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('os_family', sa.Text(), server_default='linux', nullable=False),
    sa.Column('default_user', sa.Text(), nullable=False),
    sa.Column('min_disk_gb', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default='public', nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility = 'public' AND tenant_id IS NULL) OR (visibility = 'tenant' AND tenant_id IS NOT NULL)", name=op.f('ck_images_visibility_owner')),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_images_cluster_id_provider_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_images_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index('uq_images_cluster_template_active', 'images', ['cluster_id', sa.literal_column("(provider_ref->>'vmid')")], unique=True, postgresql_where=sa.text('active'))
    op.create_table('ssh_public_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ssh_public_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_public_keys')),
    sa.UniqueConstraint('user_id', 'fingerprint', name=op.f('uq_ssh_public_keys_user_id'))
    )
    op.create_index(op.f('ix_ssh_public_keys_user_id'), 'ssh_public_keys', ['user_id'], unique=False)
    op.create_table('tenant_quotas',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('limit_value', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_quotas_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_quotas')),
    sa.UniqueConstraint('tenant_id', 'resource', name=op.f('uq_tenant_quotas_tenant_id'))
    )
    op.add_column('instances', sa.Column('image_id', sa.Uuid(), nullable=True))
    op.add_column('instances', sa.Column('ipv4', postgresql.INET(), nullable=True))
    op.add_column('instances', sa.Column('network', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index('uq_instances_cluster_ipv4_live', 'instances', ['cluster_id', 'ipv4'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND ipv4 IS NOT NULL'))
    op.create_foreign_key(op.f('fk_instances_image_id_images'), 'instances', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    platform = "current_setting('app.platform_scope', true) = 'on'"
    tenant_ok = (
        f"{platform} OR tenant_id = ANY "
        "(string_to_array(current_setting('app.tenant_ids', true), ',')::uuid[])"
    )
    for table in ("images", "ssh_public_keys", "tenant_quotas"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    # images: public ones for everybody, tenant ones for that tenant; only admins write
    op.execute(
        f"CREATE POLICY images_read ON images FOR SELECT"
        f" USING (tenant_id IS NULL OR {tenant_ok})"
    )
    op.execute(f"CREATE POLICY images_write ON images FOR ALL USING ({platform}) WITH CHECK ({platform})")
    # SSH keys: owner only (the worker reads them in platform scope)
    owner = f"{platform} OR user_id::text = current_setting('app.user_id', true)"
    op.execute(
        f"CREATE POLICY ssh_keys_owner ON ssh_public_keys FOR ALL USING ({owner}) WITH CHECK ({owner})"
    )
    # quotas: tenants read their own; only admins change them
    op.execute(f"CREATE POLICY quotas_read ON tenant_quotas FOR SELECT USING ({tenant_ok})")
    op.execute(
        f"CREATE POLICY quotas_write ON tenant_quotas FOR ALL USING ({platform}) WITH CHECK ({platform})"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_instances_image_id_images'), 'instances', type_='foreignkey')
    op.drop_index('uq_instances_cluster_ipv4_live', table_name='instances', postgresql_where=sa.text('deleted_at IS NULL AND ipv4 IS NOT NULL'))
    op.drop_column('instances', 'network')
    op.drop_column('instances', 'ipv4')
    op.drop_column('instances', 'image_id')
    op.drop_table('tenant_quotas')
    op.drop_index(op.f('ix_ssh_public_keys_user_id'), table_name='ssh_public_keys')
    op.drop_table('ssh_public_keys')
    op.drop_index('uq_images_cluster_template_active', table_name='images', postgresql_where=sa.text('active'))
    op.drop_table('images')
    # ### end Alembic commands ###
