"""Provider clusters, encrypted credentials, observed inventory and instances.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02

Cluster/node/storage/sync tables are global (admin only, no RLS). instances is
tenant-scoped with RLS; discovered guests have tenant_id NULL, so only platform scope
sees them.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_clusters',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), server_default='proxmox', nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('ca_pem', sa.Text(), nullable=True),
    sa.Column('insecure_skip_verify', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_clusters')),
    sa.UniqueConstraint('name', name=op.f('uq_provider_clusters_name'))
    )
    op.create_table('nodes',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('cpu_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memory_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('cpu_usage', sa.Float(), server_default='0', nullable=False),
    sa.Column('memory_used_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_nodes_cluster_id_provider_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('cluster_id', 'name', name=op.f('uq_nodes_cluster_id'))
    )
    op.create_table('provider_credentials',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Text(), nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('dek_wrapped', sa.LargeBinary(), nullable=False),
    sa.Column('kek_ref', sa.Text(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_provider_credentials_cluster_id_provider_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', name=op.f('pk_provider_credentials'))
    )
    op.create_table('storage_pools',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('node', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('content', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('offered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_storage_pools_cluster_id_provider_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_pools')),
    sa.UniqueConstraint('cluster_id', 'node', 'name', name=op.f('uq_storage_pools_cluster_id'))
    )
    op.create_table('sync_runs',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_sync_runs_cluster_id_provider_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_cluster_id'), 'sync_runs', ['cluster_id'], unique=False)
    op.create_table('instances',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='active', nullable=False),
    sa.Column('power_state', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('root_disk_gb', sa.Integer(), nullable=False),
    sa.Column('provider_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_name', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('managed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('missing_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT managed OR (tenant_id IS NOT NULL AND project_id IS NOT NULL)', name=op.f('ck_instances_managed_has_owner')),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_instances_cluster_id_provider_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_instances_node_id_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_instances_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_instances_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances'))
    )
    op.create_index('ix_instances_tenant_project', 'instances', ['tenant_id', 'project_id'], unique=False)
    op.create_index('uq_instances_cluster_guest_live', 'instances', ['cluster_id', sa.literal_column("(provider_ref->>'vmid')")], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

    tenant_ok = (
        "current_setting('app.platform_scope', true) = 'on' OR tenant_id = ANY "
        "(string_to_array(current_setting('app.tenant_ids', true), ',')::uuid[])"
    )
    op.execute("ALTER TABLE instances ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY instances_isolation ON instances FOR ALL"
        f" USING ({tenant_ok}) WITH CHECK ({tenant_ok})"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_instances_cluster_guest_live', table_name='instances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_instances_tenant_project', table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_sync_runs_cluster_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('storage_pools')
    op.drop_table('provider_credentials')
    op.drop_table('nodes')
    op.drop_table('provider_clusters')
    # ### end Alembic commands ###
