"""Regions and zones; images become logical with per-server templates (ADR-0012).

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 23:37:06.029007
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('slug', name=op.f('uq_regions_slug'))
    )
    op.create_table('zones',
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_zones_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('slug', name=op.f('uq_zones_slug'))
    )
    op.create_index(op.f('ix_zones_region_id'), 'zones', ['region_id'], unique=False)
    op.create_table('image_templates',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('provider_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['provider_clusters.id'], name=op.f('fk_image_templates_cluster_id_provider_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_templates_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_templates')),
    sa.UniqueConstraint('image_id', 'cluster_id', name=op.f('uq_image_templates_image_id'))
    )
    op.create_index(op.f('ix_image_templates_image_id'), 'image_templates', ['image_id'], unique=False)
    op.create_index('uq_image_templates_cluster_template', 'image_templates', ['cluster_id', sa.literal_column("(provider_ref->>'vmid')")], unique=True)
    # move each image's template into image_templates before dropping the columns
    # (min_disk_gb of the image was the template's disk, so it is the template's too)
    op.execute(
        "INSERT INTO image_templates (id, image_id, cluster_id, provider_ref, disk_gb)"
        " SELECT gen_random_uuid(), id, cluster_id, provider_ref, min_disk_gb FROM images"
    )
    op.drop_index(op.f('uq_images_cluster_template_active'), table_name='images', postgresql_where='active')
    op.drop_constraint(op.f('fk_images_cluster_id_provider_clusters'), 'images', type_='foreignkey')
    op.drop_column('images', 'provider_ref')
    op.drop_column('images', 'cluster_id')
    op.add_column('provider_clusters', sa.Column('zone_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_provider_clusters_zone_id'), 'provider_clusters', ['zone_id'], unique=False)
    op.create_foreign_key(op.f('fk_provider_clusters_zone_id_zones'), 'provider_clusters', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_provider_clusters_zone_id_zones'), 'provider_clusters', type_='foreignkey')
    op.drop_index(op.f('ix_provider_clusters_zone_id'), table_name='provider_clusters')
    op.drop_column('provider_clusters', 'zone_id')
    op.add_column('images', sa.Column('cluster_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('provider_ref', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_images_cluster_id_provider_clusters'), 'images', 'provider_clusters', ['cluster_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_images_cluster_template_active'), 'images', ['cluster_id', sa.literal_column("(provider_ref ->> 'vmid'::text)")], unique=True, postgresql_where='active')
    op.drop_index('uq_image_templates_cluster_template', table_name='image_templates')
    op.drop_index(op.f('ix_image_templates_image_id'), table_name='image_templates')
    op.drop_table('image_templates')
    op.drop_index(op.f('ix_zones_region_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('regions')
    # ### end Alembic commands ###
