"""Identity, tenancy, RBAC catalog, auth sessions and audit log, with RLS.

Revision ID: 0001
Revises:
Create Date: 2026-10-02

Runs as cm_owner. Table privileges for cm_app come from the default privileges set in
deploy/docker/postgres/init/01-roles.sh; this migration only narrows them.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_occurred', 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_occurred', 'audit_logs', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_permissions'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allowed_scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('tenants',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('uq_projects_tenant_slug_live', 'projects', ['tenant_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('role_bindings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(scope_type = 'platform' AND scope_id IS NULL AND tenant_id IS NULL) OR (scope_type = 'tenant' AND scope_id = tenant_id) OR (scope_type = 'project' AND scope_id IS NOT NULL AND tenant_id IS NOT NULL)", name=op.f('ck_role_bindings_scope_consistent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_role_bindings_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_bindings_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_role_bindings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_bindings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_bindings')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_role_bindings_user_role_scope', postgresql_nulls_not_distinct=True)
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['permissions.name'], name=op.f('fk_role_permissions_permission_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amr', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name=op.f('uq_tenant_memberships_tenant_id'))
    )
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_user_id'), 'role_bindings', ['user_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_tenant_id'), 'role_bindings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    _privileges()
    _row_level_security()


# Predicates shared by the policies (docs/architecture/03-tenancy-e-rbac.md).
# Unset settings yield NULL / empty array, so a session without scope sees nothing.
PLATFORM = "current_setting('app.platform_scope', true) = 'on'"


def _tenant_ok(col: str) -> str:
    return (
        f"({PLATFORM} OR {col} = ANY "
        "(string_to_array(current_setting('app.tenant_ids', true), ',')::uuid[]))"
    )


def _user_ok(col: str) -> str:
    # compared as text: '' (setting reset after a previous transaction) is not a valid uuid
    return f"({col}::text = current_setting('app.user_id', true))"


def _privileges() -> None:
    op.execute("REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON alembic_version FROM cm_app")
    # RBAC catalog is seeded by `python -m app.cli migrate` (as cm_owner), read-only at runtime
    op.execute(
        "REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON permissions, roles, role_permissions FROM cm_app"
    )
    # append-only audit trail
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM cm_app")


def _policy(table: str, name: str, command: str, using: str | None, check: str | None) -> None:
    sql = f"CREATE POLICY {name} ON {table} FOR {command}"
    if using:
        sql += f" USING ({using})"
    if check:
        sql += f" WITH CHECK ({check})"
    op.execute(sql)


def _row_level_security() -> None:
    # No FORCE: the owner (cm_owner) bypasses RLS; cm_app is not the owner, so it never does.
    for table in ("tenants", "tenant_memberships", "projects", "role_bindings", "audit_logs"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

    is_member = (
        "EXISTS (SELECT 1 FROM tenant_memberships m WHERE m.tenant_id = tenants.id"
        f" AND {_user_ok('m.user_id')})"
    )
    _policy("tenants", "tenants_read", "SELECT", f"{_tenant_ok('id')} OR {is_member}", None)
    _policy("tenants", "tenants_write", "ALL", _tenant_ok("id"), _tenant_ok("id"))

    # a user always sees their own memberships/bindings (to list tenants, resolve permissions)
    for table in ("tenant_memberships", "role_bindings"):
        _policy(
            table, f"{table}_read", "SELECT",
            f"{_tenant_ok('tenant_id')} OR {_user_ok('user_id')}", None,
        )
        _policy(table, f"{table}_write", "ALL", _tenant_ok("tenant_id"), _tenant_ok("tenant_id"))

    _policy("projects", "projects_isolation", "ALL", _tenant_ok("tenant_id"), _tenant_ok("tenant_id"))

    # anyone may append (e.g. LOGIN_FAILED has no tenant); reading is tenant-scoped
    _policy("audit_logs", "audit_logs_read", "SELECT", _tenant_ok("tenant_id"), None)
    _policy("audit_logs", "audit_logs_append", "INSERT", None, "true")


def downgrade() -> None:
    # policies are dropped with their tables
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_bindings_tenant_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_user_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('role_bindings')
    op.drop_index('uq_projects_tenant_slug_live', table_name='projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('projects')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ix_audit_logs_tenant_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_occurred', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
