"""Observed provider pool of each instance (writes only inside the managed pool).

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-03 00:09:59.503702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('provider_pool', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # until the next sync fills it, keep the guests the platform created operable
    op.execute(
        "UPDATE instances SET provider_pool = provider_ref->>'pool' WHERE provider_ref ? 'pool'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'provider_pool')
    # ### end Alembic commands ###
